# Generated by Django 4.2.2 on 2023-08-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_mymessages_agent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessages',
            name='msg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
