# Generated by Django 4.2.2 on 2023-07-14 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
